version: "3.3"

services:
  sisfin-frontend:
    build: ../sisfin-frontend/
    image: img_sisfin_frontend_dev:0.1
    container_name: con_sisfin_frontend_dev
    restart: always
    ports:
      - 8180:8180
    networks:
      - net_sisfin_dev
    volumes:
      - "C:\\development\\projects\\sisfin-docker-workspace\\sisfin-frontend:/app"

networks:
  net_sisfin_dev:
    name: net_sisfin_dev